config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get "about" => "public#about", as: 'about'
  get "blog" => "public#blog", as: 'blog'
  get "contact" => "public#contact", as: 'contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    root to: "public#homepage"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates_presence_of :title, :url
    has_many :posts 

    def total 
        post.count
    end
end

app/models/post.rb
class Post < ApplicationRecord
    validates :Title, presence: true
    validates :body, presence: true, length: { minimum: 2 }
    validates :summary, presence: true
    
   belongs_to :category

   after_create :update_total_posts_count

   private

   def update_total_posts_count

    category.increment(:total_count, 1)
    
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:Title, :summary, :body, :active)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    
    def homepage
        @posts= Post.all
    end

    def about
    end
    
    def contact
    end
    
    def blog
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title title
         content_for :page_title, title.to_s
    end
end

app/helpers/catigories_helper.rb
module CatigoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

app/views/layouts/_menu.html.erb
<h1 class="float-start"> Rails blog</h1>

<ul class="float-end list-unstyled list-inline">
    <li class="list-inline-item"><%= link_to "Home", root_path %></li>
    <li class="list-inline-item"><%= link_to "About", about_path %></li>
    <li class="list-inline-item"><%= link_to "Blog", blog_path %></li>
    <li class="list-inline-item"><%= link_to "Contact", contact_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : "Ruby on Rails Blog" %> | Udemy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col">
         <%= render partial: "layouts/menu" %>
        </div>
      </div>
    </div>
    <div class="container"">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render partial: "layouts/footer" %>
    <%= yield(:scripts) if content_for?(:scripts) %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Title, style: "display: block" %>
    <%= form.text_field :Title %>
  </div>

  <div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_field :summary %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<h3><%= link_to post.Title, post_path(post) %></h3>
<p><%= post.summary %></p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render @post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.Title %></h1>

<%= @post.details %>
<%= simple_format @post.body %>
<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>